name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v3
        with:
          name: spdx-report
          path: spdx.json
